name: scala-udfs
description: ''
version: '0.1'
author: nimbus@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalaudfs
  parentArtefactID: prophecy_nimbus_team
  buildSystem: maven
  author: null
  createdAt: '2023-09-11 18:29:20'
pipelines:
  pipelines/functions:
    name: functions
    description: ''
    author: nimbus@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-09-11 18:29:20'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-09-11 18:29:20'
  gems: {}
  udfs:
    udfs/test:
      name: test
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nimbus@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
