name: scala-udfs
description: ''
version: 0.0.1
author: nimbus@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: scalaudfs
  parentArtefactID: prophecy_nimbus_team
  buildSystem: maven
  author: null
  createdAt: '2023-09-11 18:29:20'
pipelines:
  pipelines/functions:
    name: functions
    description: ''
    author: nimbus@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2023-09-11 18:29:20'
    datasets:
      inputs: []
      outputs:
      - datasets/json_out
    subgraphs: []
    dependencies: {}
datasets:
  datasets/json_out:
    name: json_out
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-28 21:14:41'
    mode: batch
    physicalDatasets:
      product-workspace:
        fabricId: 4615
        datasetType: File
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-28 21:14:41'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.0.4
  gems: {}
functions:
  author: null
  createdAt: '2023-09-11 18:29:20'
  udfs:
    udfs/mult_self:
      name: mult_self
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: nimbus@prophecy.io
      createdAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2023-09-28 08:42:10'
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2023-09-28 08:42:10'
pipelineConfigurations: {}
